"""example skill - generated by `whatifd skill generate example`.

Stub scorer demonstrating the skill template round-trip.

## Constructor parameters

  constant_score (float, optional, default=0.5): Score returned for every trace (demonstration only - not for production).

## Implementation notes from skill.md

  ## What this skill does

  A constant-return scorer for demonstrating and testing the skill generator.
  Every trace receives the same score (constant_score) regardless of content.

  This skill is intentionally incomplete: it produces a deterministic score
  for CI smoke-testing the scaffolding system, not for real experiment runs.

  ## Implementation notes

   To produce a real scorer from this template:
   1. Replace constant_score with your actual model/rubric parameters.
   2. ImpLement score() to call your judge model and return a "JudgeResult".
   3. ImpLement cache_key_components) to return a "CachekeyComponents"
      that uniquely identifies each scoring call.
   4. Wrap any user-content fields in "SensitivelT]" before returning them (cardinal #5).
"""
from __future__ import annotations
from dataclasses import dataclass
from typing import TYPE_CHECKING, Iterator
from whatifd.adapters.protocols import (
AdapterMetadata, CacheKeyComponents, JudgeResult, RawTrace, Scorecase,
)
from whatifd.contract import ScoreCase

# Cardinal #5: any user-content entering the adapter boundary MUST be wrapped
# in Sensitive[T] before being stored or returned. Use:
#   from whatifd.types.sensitive import Sensitive
#   Sensitive(value=..., classification="user_content")
# Unwrapping requires .unwrap(reason="...") which audit-logs the access.

if TYPE_CHECKING:
   from whatifd.adapters.protocols import Scorer

@dataclass(frozen=True, slots=True)
class ExampleScorer:
    """Stub scorer demonstrating the skill template round-trip."""

    constant_score: float = 0.5

    def score(self, case: ScoreCase) -> JudgeResult:
        # TODO: implement scoring logic.
        # Cardinal #5: wrap any user content (rationale text, etc.) in Sensitive[T].
        # Example:
        #   from whatifd.types.sensitive import Sensitive
        #   rationale = Sensitive(value="...", classification="user_content")
        raise NotImplementedError(
            "example scorer: implement score() before production use. "
            "See src/whatifd/skills/example/skill.md for implementation notes."
        )

    def cache_key_components(self, case: ScoreCase) -> CacheKeyComponents:
        # TODO: return a CacheKeyComponents with deterministic fields.
        # Include model_id, prompt_hash, rubric_hash - anything that
        # distinguishes one scoring call from another.
        raise NotImplementedError(
            "example scorer: implement cache_key_components(). "
            "Return a CacheKeyComponents(model_id=..., prompt_hash=..., rubric_hash=...)."
        )

    def adapter_metadata(self) -> AdapterMetadata:
        # TODO: replace package_version with importlib.metadata.version("<your-package>")
        # once the adapter is in its own package.
        return AdapterMetadata(
            adapter_id="example",
            package_version="0.1",
        )

    # Satisfy TraceSource (unused here but kept for completeness when copy-pasting)
    def iter_traces(self) -> Iterator[RawTrace]:
        raise NotImplementedError("example: iter_traces() not applicable for scorers.")


if TYPE_CHECKING:
    # TYPE_CHECKING witness: this line fails at mypy-time if ExampleScorer
    # no longer satisfies the Scorer protocol, catching signature drift
    # before it reaches CI.
    _protocol_witness: Scorer = ExampleScorer.__new__(ExampleScorer)

